server:
  port: 8081
spring:
  application:
    name: "Solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "https://idp.example.com/issuer"
          client-id: "myclientid"
jwt:
  json-exp-roles: "/roles"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapters:
  r2dbc:
    host: 127.0.0.1
    port: 5432
    database: crediya
    schema: public
    username: postgres
    password: HTCjdg1998#

logging:
  level:
    root: ERROR



springdoc:
  swagger-ui:
    url: /openapi.yaml
    path: /swagger-ui.html
    disable-swagger-default-url: true

logging_collector: "on"
log_statement: "all"                # para logear todas las consultas
log_min_duration_statement: 0       # logear todas las consultas, incluso rápidas
log_directory: "pg_log"
log_filename: "postgresql-%Y-%m-%d_%H%M%S.log"
